### PR TITLE
Fix memory leak, upgrade gradle wrapper

### PR DESCRIPTION
**Pull request by Andrew-Bekhiet**
In this PR:
Fixes a memory leak in file input stream, which caused a lot of bugs like missing plugin exception
Upgrades gradle wrapper
Updates .gitignore to match flutter recommendation

### CODE REVIEW

**Comment by ZoftPranav** [comment]
@Andrew-Bekhiet  hey can you help me out I would very much like an updated version of this plugin to work on iOS and android the latest android Gradle changes and iOS issues prevent me from using this plugin

**Comment by adekmaulana** [comment]
> @Andrew-Bekhiet hey can you help me out I would very much like an updated version of this plugin to work on iOS and android the latest android Gradle changes and iOS issues prevent me from using this plugin

use my repo it's updated and running with ios, it based from @Andrew-Bekhiet repo

**Comment by ZoftPranav** [comment]
@Andrew-Bekhiet  how can I use it in pubspec.yaml file?

**Comment by Andrew-Bekhiet** [comment]
> @Andrew-Bekhiet how can I use it in pubspec.yaml file?

To use my repo, add these lines:
```yaml
dependencies:
  get_thumbnail_video:
    git:
      url: https://github.com/Andrew-Bekhiet/video_thumbnail
      ref: master
```

To use adekmaulana's repo:
```yaml
dependencies:
  get_thumbnail_video:
    git:
      url: https://github.com/adekmaulana/video_thumbnail
      ref: master
```

**Comment by Alberto-Monteiro** [comment]
Thank you all for your valuable contributions to the project! However, I had to make structural changes to the code, which prevented me from directly merging the PR.

The necessary adjustments have been made, and version 0.7.2 is now available.

**Pull request closed without merging**
